# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 18:01
from __future__ import unicode_literals

from django.db import migrations
import home.models
import home.snippets
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corecontentpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('list_block_cornerstone_snippet', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('description', wagtail.wagtailcore.blocks.CharBlock()), ('snippet', home.models.SnippetChooserBlock(home.snippets.Footer)))))),), blank=True, null=True),
        ),
    ]
