# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 19:42
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementspage',
            name='attributes',
        ),
        migrations.AlterField(
            model_name='elementspage',
            name='types',
            field=wagtail.core.fields.StreamField((('types', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock(required=True)), ('detail', wagtail.core.blocks.CharBlock(required=True))))),), blank=True, null=True),
        ),
    ]
