# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 21:06
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171003_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementspage',
            name='options',
            field=wagtail.wagtailcore.fields.StreamField((('options', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('detail', wagtail.wagtailcore.blocks.CharBlock(required=True))))),), blank=True, null=True),
        ),
    ]
