# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_elementspage_options'),
        ('home', '0002_auto_20171003_1837'),
    ]

    operations = [
    ]
