# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('home', '0004_auto_20171004_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_descriptors', to='home.ElementDescriptor')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_descriptortag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatItDoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'What it does',
            },
        ),
        migrations.CreateModel(
            name='WhatUserCanDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'What user can do',
            },
        ),
        migrations.CreateModel(
            name='WhenToUseIt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'When to use it',
            },
        ),
        migrations.AddField(
            model_name='elementspage',
            name='what_it_does',
            field=models.ForeignKey(blank=True, help_text='select a snippet from the what it does type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.WhatItDoes', verbose_name='What it does'),
        ),
        migrations.AddField(
            model_name='elementspage',
            name='what_user_can_do',
            field=models.ForeignKey(blank=True, help_text='select a snippet from the what user can do type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.WhatUserCanDo', verbose_name='What user can do'),
        ),
        migrations.AddField(
            model_name='elementspage',
            name='when_to_use_it',
            field=models.ForeignKey(blank=True, help_text='select a snippet from the when to use it type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.WhenToUseIt', verbose_name='When to use it'),
        ),
    ]
