# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('home', '0004_merge_20171003_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_descriptors', to='home.ElementDescriptor')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_descriptortag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
