# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 13:32
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171005_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementspage',
            name='types',
            field=wagtail.core.fields.StreamField((('types', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock(required=True)), ('detail', wagtail.core.blocks.CharBlock(required=True)))))),), blank=True, null=True),
        ),
    ]
