# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_descriptortag'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatItDoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'What it does',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatUserCanDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'What user can do',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhenToUseIt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'When to use it',
                'ordering': ['name'],
            },
        ),
    ]
