# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_whatitdoes_whatusercando_whentouseit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementspage',
            name='what_it_does',
            field=models.ForeignKey(blank=True, help_text='select a snippet from the what it does type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.WhatItDoes', verbose_name='What it does'),
        ),
        migrations.AlterField(
            model_name='elementspage',
            name='what_user_can_do',
            field=models.ForeignKey(blank=True, help_text='select a snippet from the what user can do type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.WhatUserCanDo', verbose_name='What user can do'),
        ),
        migrations.AlterField(
            model_name='elementspage',
            name='when_to_use_it',
            field=models.ForeignKey(blank=True, help_text='select a snippet from the when to use it type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.WhenToUseIt', verbose_name='When to use it'),
        ),
    ]
