# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 13:41
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171020_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementspage',
            name='types',
            field=wagtail.wagtailcore.fields.StreamField((('types', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('detail', wagtail.wagtailcore.blocks.CharBlock(required=True))))),), blank=True, null=True),
        ),
    ]
