# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0010_blockspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBase',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('wagtailcore.page',),
        ),
    ]
