# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20171030_1650'),
        ('home', '0012_auto_20171102_2116'),
    ]

    operations = [
    ]
