# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_20171102_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='corecontentpage',
            name='menu_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='menu_order',
            field=models.IntegerField(default=0),
        ),
    ]
