# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 18:22
from __future__ import unicode_literals

from django.db import migrations
import home.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20171107_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corecontentpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('html', wagtail.core.blocks.RichTextBlock()), ('image', home.models.APIImageChooserBlock())), blank=True, null=True),
        ),
    ]
