# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 15:13
from __future__ import unicode_literals

from django.db import migrations
import home.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtailmarkdownblock.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20171129_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corecontentpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('html', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', home.models.APIImageChooserBlock()), ('markdown', wagtailmarkdownblock.blocks.MarkdownBlock())), blank=True, null=True),
        ),
    ]
