# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 20:22
from __future__ import unicode_literals

from django.db import migrations
import home.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20171205_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corecontentpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('richText', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', home.models.APIImageChooserBlock()), ('markdown', home.models.APIMarkDownBlock())), blank=True, null=True),
        ),
    ]
