# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_footertext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterText',
        ),
    ]
