# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_advert'),
    ]

    operations = [
        migrations.CreateModel(
            name='CornerStones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Advert',
        ),
    ]
