# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20170921_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cornerstones',
            options={'verbose_name': 'Cornerstone', 'verbose_name_plural': 'Cornerstones'},
        ),
    ]
