# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20170921_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cornerstones',
            name='description',
            field=models.TextField(),
        ),
    ]
