# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20180103_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementspage',
            name='fka',
            field=models.CharField(blank=True, max_length=255, verbose_name='Formerly Known As'),
        ),
    ]
