# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_elementspage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockspage',
            name='cross_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cross Link'),
        ),
        migrations.AddField(
            model_name='elementspage',
            name='cross_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cross Link'),
        ),
    ]
