# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20170921_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CornerStones',
        ),
    ]
