# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 16:15
from __future__ import unicode_literals

from django.db import migrations
import home.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20180206_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockspage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('richText', home.models.APIRichTextBlock()), ('image', home.models.APIImageChooserBlock()), ('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('markdown', home.models.APIMarkDownBlock())), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elementspage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('richText', home.models.APIRichTextBlock()), ('markdown', home.models.APIMarkDownBlock()), ('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('image', home.models.APIImageChooserBlock())), blank=True, null=True),
        ),
    ]
