# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20180215_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='corecontentpage',
            name='cross_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cross Link'),
        ),
    ]
