# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_corecontentpage_cross_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockspage',
            name='demo_link',
            field=models.CharField(blank=True, help_text='i.e. code/ids-web/latest/demo/ids-button/index.html', max_length=255, verbose_name='Demo Link'),
        ),
        migrations.AddField(
            model_name='corecontentpage',
            name='demo_link',
            field=models.CharField(blank=True, help_text='i.e. code/ids-web/latest/demo/ids-button/index.html', max_length=255, verbose_name='Demo Link'),
        ),
        migrations.AddField(
            model_name='elementspage',
            name='demo_link',
            field=models.CharField(blank=True, help_text='i.e. code/ids-web/latest/demo/ids-button/index.html', max_length=255, verbose_name='Demo Link'),
        ),
        migrations.AlterField(
            model_name='blockspage',
            name='cross_link',
            field=models.CharField(blank=True, help_text='i.e. button', max_length=255, verbose_name='Cross Link'),
        ),
        migrations.AlterField(
            model_name='corecontentpage',
            name='cross_link',
            field=models.CharField(blank=True, help_text='i.e. button', max_length=255, verbose_name='Cross Link'),
        ),
        migrations.AlterField(
            model_name='elementspage',
            name='cross_link',
            field=models.CharField(blank=True, help_text='i.e. button', max_length=255, verbose_name='Cross Link'),
        ),
    ]
