# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_corecontentpage_cross_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockspage',
            name='demo_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Demo Link'),
        ),
        migrations.AddField(
            model_name='corecontentpage',
            name='demo_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Demo Link'),
        ),
        migrations.AddField(
            model_name='elementspage',
            name='demo_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Demo Link'),
        ),
    ]
