# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 00:06
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20180307_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockspage',
            name='options',
            field=wagtail.wagtailcore.fields.StreamField((('options', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('detail', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('token', wagtail.wagtailcore.blocks.CharBlock(required=False))), label='Modifiers')),), blank=True, null=True, verbose_name='Modifiers'),
        ),
        migrations.AlterField(
            model_name='elementspage',
            name='options',
            field=wagtail.wagtailcore.fields.StreamField((('options', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('detail', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('token', wagtail.wagtailcore.blocks.CharBlock(required=False))), label='Modifiers')),), blank=True, null=True, verbose_name='Modifiers'),
        ),
    ]
