# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20180307_1626'),
    ]

    operations = [
        migrations.RenameField('blockspage', 'options', 'modifiers'),
        migrations.RenameField('elementspage', 'options', 'modifiers'),
    ]
