# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-19 19:50
from __future__ import unicode_literals

from django.db import migrations
import home.models
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20180308_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockspage',
            name='tokens',
            field=wagtail.wagtailcore.fields.StreamField((('tokens', wagtail.wagtailcore.blocks.StructBlock((('design_token', wagtail.wagtailcore.blocks.CharBlock()), ('color', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('value', wagtail.wagtailcore.blocks.CharBlock())))),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementspage',
            name='tokens',
            field=wagtail.wagtailcore.fields.StreamField((('tokens', wagtail.wagtailcore.blocks.StructBlock((('design_token', wagtail.wagtailcore.blocks.CharBlock()), ('color', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('value', wagtail.wagtailcore.blocks.CharBlock())))),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockspage',
            name='modifiers',
            field=wagtail.wagtailcore.fields.StreamField((('options', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('detail', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('token', wagtail.wagtailcore.blocks.CharBlock(required=False))))),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corecontentpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('image', home.models.APIImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('markdown', home.models.APIMarkDownBlock()), ('tokens', wagtail.wagtailcore.blocks.StructBlock((('design_token', wagtail.wagtailcore.blocks.CharBlock()), ('color', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('value', wagtail.wagtailcore.blocks.CharBlock()))))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elementspage',
            name='modifiers',
            field=wagtail.wagtailcore.fields.StreamField((('options', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('detail', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('token', wagtail.wagtailcore.blocks.CharBlock(required=False))))),), blank=True, null=True),
        ),
    ]
