# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 20:36
from __future__ import unicode_literals

from django.db import migrations
import home.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20180321_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='page_hero',
            field=wagtail.wagtailcore.fields.StreamField((('page_hero', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('image', home.models.APIImageChooserBlock(required=True)), ('text_color', wagtail.wagtailcore.blocks.CharBlock(help_text='enter hex code without #', required=True)), ('background_color', wagtail.wagtailcore.blocks.CharBlock(help_text='enter hex code without #', required=True))))),), blank=True, null=True),
        ),
    ]
