# Generated by Django 2.0.4 on 2018-04-05 15:48

from django.db import migrations
import home.models
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20180405_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockspage',
            name='body',
            field=wagtail.core.fields.StreamField((('image', home.models.APIImageChooserBlock()), ('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('richText', home.models.APIRichTextBlock()), ('markdown', home.models.APIMarkDownBlock())), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corecontentpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('image', home.models.APIImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('markdown', home.models.APIMarkDownBlock()), ('richText', home.models.APIRichTextBlock()), ('tokensCategory', wagtail.core.blocks.CharBlock())), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elementspage',
            name='body',
            field=wagtail.core.fields.StreamField((('markdown', home.models.APIMarkDownBlock()), ('richText', home.models.APIRichTextBlock()), ('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('image', home.models.APIImageChooserBlock())), blank=True, null=True),
        ),
    ]
