# Generated by Django 2.0.4 on 2018-04-20 20:38

from django.db import migrations, models
import django.db.models.deletion
import home.models
import wagtail.contrib.table_block.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0039_auto_20180405_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('menu_order', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('home.pagebase',),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Author')),
                ('content', wagtail.core.fields.StreamField((('markdown', home.models.APIMarkDownBlock()), ('richText', home.models.APIRichTextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())), blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('home.pagebase',),
        ),
    ]
