# Generated by Django 2.1.2 on 2019-02-06 18:57

from django.db import migrations
import home.models
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_bloglandingpage_blogpostpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corecontentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('image', home.models.APIImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('markdown', home.models.APIMarkDownBlock()), ('richText', home.models.APIRichTextBlock()), ('tokensCategory', wagtail.core.blocks.CharBlock()), ('iconType', wagtail.core.blocks.CharBlock(label='Icon Type'))], blank=True, null=True),
        ),
    ]
