# Generated by Django 2.1.7 on 2019-05-02 14:47

from django.db import migrations
import home.models
import wagtail.contrib.table_block.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_libversions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='content',
            field=wagtail.core.fields.StreamField([('image', home.models.APIImageChooserBlock()), ('markdown', home.models.APIMarkDownBlock()), ('richText', home.models.APIRichTextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True),
        ),
    ]
