#!/bin/bash


eb setenv AWS_STORAGE_BUCKET_NAME="$AWS_STORAGE_BUCKET_NAME" \
    AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
    AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
    DEBUG="$DEBUG" \
    RDS_TRUE="True" \
    S3_TRUE="True"
