language: node_js
node_js:
  - 9
# @TODO: fix sudo workaround
# https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524
sudo: required
before_script:
  - cd src/web
  - npm install
  - npm run lint
script:
  - npx karma start ./karma.conf.js --single-run
