language: node_js
node_js:
  - 11
addons:
  - chrome: stable
cache:
  directories:
    - node_modules
before_script:
  - cd src/site
  - npm install
  - npm run lint
  - npm run test -- --watch=false
script:
  - npm run build
