version: '3'

volumes:
  static-data:
    driver: local
  media-data:
    driver: local
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:9.6.1
    container_name: 'docssite_postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./docker/docs-backend
    image: hookandloop/docs-backend:1.0.1
    container_name: 'docssite_backend'
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./src/app:/home/app

      - ./src/config:/home/config
      - ./src/config/supervisor/backend.conf:/etc/supervisor/conf.d/backend.conf

      - static-data:/home/app/static/
      - media-data:/home/app/media/
    ports:
      - "9003"
      - "9002:9002"
    environment:
      ROOT_URL_PATH: ${ROOT_URL_PATH}
      S3_STORAGE: ${S3_STORAGE}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      AWS_QUERYSTRING_AUTH: ${AWS_QUERYSTRING_AUTH}

  nginx:
    build: ./docker/docs-nginx
    image: hookandloop/docs-nginx:1.0.0
    container_name: 'docssite_nginx'
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - ./src/web:/home/web

      - ./src/config:/home/config
      - ./src/config/supervisor/webserver.conf:/etc/supervisor/conf.d/webserver.conf
      - ./src/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/config/nginx/localhost.conf:/etc/nginx/sites-available/default

      - static-data:/home/app/static/
      - media-data:/home/app/media/
    ports:
      - "80:80"
