version: '3'

volumes:
  static-data:
    driver: local
  media-data:
    driver: local
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./docker/docs-backend
    image: hookandloop/docs-backend:1.0.0
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./src/app:/home/app

      - ./src/config:/home/config
      - ./src/config/supervisor/backend.conf:/etc/supervisor/conf.d/backend.conf

      - static-data:/home/app/static/
      - media-data:/home/app/media/
    ports:
      - "9000:9000"
      - "9001:9001"

  nginx:
    build: ./docker/docs-nginx
    image: hookandloop/docs-nginx:1.0.0
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - ./src/web:/home/web

      - ./src/config:/home/config
      - ./src/config/supervisor/webserver.conf:/etc/supervisor/conf.d/webserver.conf
      - ./src/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/config/nginx/localhost.conf:/etc/nginx/sites-available/default

      - static-data:/home/app/static/
      - media-data:/home/app/media/
    ports:
      - "80:80"
