# Generated by Django 2.0.8 on 2018-10-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='pageSlug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
