# Generated by Django 2.0.8 on 2018-10-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_pageslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='pageSlug',
            new_name='page_slug',
        ),
    ]
