# Generated by Django 2.0.8 on 2018-10-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20181001_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='page_slug',
            new_name='relative_url',
        ),
    ]
