# Generated by Django 2.0.8 on 2018-10-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20181002_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='thumbs_down',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='thumbs_up',
        ),
        migrations.AddField(
            model_name='feedback',
            name='thumb_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
