# Generated by Django 2.0.8 on 2018-10-02 19:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Json format')),
                ('meta_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Json format')),
                ('relative_url', models.CharField(default='', max_length=100)),
                ('thumb_type', models.CharField(default='', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'All Feedback Objects',
                'verbose_name': 'Feedback',
                'ordering': ('-date_updated', '-date_created'),
            },
        ),
    ]
